
# builder-image:
#   image: docker:cli
#   services:
#     - docker:dind
#   variables:
#     DOCKER_IMAGE_NAME: $CI_REGISTRY_IMAGE/builder-base:$CI_COMMIT_REF_SLUG
#   before_script:
#     - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
#   script:
#     - docker build -t $DOCKER_IMAGE_NAME ./builder
#     - docker push $DOCKER_IMAGE_NAME
#     - |
#       if [[ "$CI_COMMIT_BRANCH" == "$CI_DEFAULT_BRANCH" ]]; then
#         docker tag "$DOCKER_IMAGE_NAME" "$CI_REGISTRY_IMAGE:latest"
#         docker push "$CI_REGISTRY_IMAGE:latest"
#       fi

build-mangosd-default:
  parallel:
    matrix:
      - CORE:
        - classic
        - tbc
        - wotlk
      - IMAGE_TAG: latest
      - BUILD_ARGS: ""
  script:
    - echo "Building $CI_REGISTRY_IMAGE/cmangos-mangosd-$CORE:$IMAGE_TAG"
    - echo "$BUILD_ARGS"

build-mangosd-with-playerbot:
  parallel:
    matrix:
      - CORE:
        - classic
        - tbc
        - wotlk
      - IMAGE_TAG: with-playerbot
      - BUILD_ARGS: BUILD_PLAYERBOT=ON
  script:
    - echo "Building $CI_REGISTRY_IMAGE/cmangos-mangosd-$CORE:$IMAGE_TAG"
    - echo "$BUILD_ARGS"

build-mangosd-with-ahbot:
  parallel:
    matrix:
      - CORE:
        - classic
        - tbc
        - wotlk
      - IMAGE_TAG: with-ahbot
      - BUILD_ARGS: BUILD_AHBOT=ON
  script:
    - echo "Building $CI_REGISTRY_IMAGE/cmangos-mangosd-$CORE:$IMAGE_TAG"
    - echo "$BUILD_ARGS"

build-mangosd-with-playerbot-ahbot:
  parallel:
    matrix:
      - CORE:
        - classic
        - tbc
        - wotlk
      - IMAGE_TAG: with-playerbot-ahbot
      - BUILD_ARGS: BUILD_PLAYERBOT=ON BUILD_AHBOT=ON
  script:
    - echo "Building $CI_REGISTRY_IMAGE/cmangos-mangosd-$CORE:$IMAGE_TAG"
    - echo "$BUILD_ARGS"