services:
  database:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: "${DB_ROOT_PASS:-mangos}"
      MYSQL_USER: "${DB_USER:-mangos}"
      MYSQL_PASSWORD: "${DB_PASS:-mangos}"
    ports:
      - "${DB_PORT:-3306}:3306"
    volumes:
      - "./data/${CORE_VARIANT}/database:/var/lib/mysql"

  realmd:
    build:
      context: ./realmd/
      dockerfile: Dockerfile
      args:
        CMANGOS_CORE: ${CORE_VARIANT}
    image: registry.int.jrtashjian.com/jrtashjian/cmangos-docker/realmd-${CORE_VARIANT}:latest
    depends_on:
      - database
    env_file: .env
    ports:
      - 3724:3724
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "./data/${CORE_VARIANT}/realmd_etc:/opt/cmangos/etc"

  mangosd:
    build:
      context: ./mangosd/
      dockerfile: Dockerfile
      args:
        CMANGOS_CORE: ${CORE_VARIANT}
    image: registry.int.jrtashjian.com/jrtashjian/cmangos-docker/mangosd-${CORE_VARIANT}:latest
    depends_on:
      - database
      - realmd
    env_file: .env
    ports:
      - 8085:8085
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "./data/${CORE_VARIANT}/mangosd_etc:/opt/cmangos/etc"
      - "./extracted-data/${CORE_VARIANT}:/opt/cmangos-data:ro"
