version: "3.5"

services:
  database:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: "${DB_ROOT_PASS:-mangos}"
      MYSQL_USER: "${DB_USER:-mangos}"
      MYSQL_PASSWORD: "${DB_PASS:-mangos}"
    ports:
      - "${DB_PORT:-3306}:3306"
    volumes:
      - "./data/database:/var/lib/mysql"

  realmd:
    image: ghcr.io/jrtashjian/cmangos-realmd-tbc:latest
    depends_on:
      - database
    environment:
      DB_HOST: "${DB_HOST:-database}"
      DB_PORT: "${DB_PORT:-3306}"
      DB_USER: "${DB_USER:-mangos}"
      DB_PASS: "${DB_PASS:-mangos}"
      DB_ROOT_PASS: "${DB_ROOT_PASS:-mangos}"
    ports:
      - 3724:3724
    volumes:
      - "./data/realmd_etc:/opt/cmangos/etc"
      - "/etc/localtime:/etc/localtime:ro"

  mangosd:
    image: ghcr.io/jrtashjian/cmangos-mangosd-tbc:latest
    depends_on:
      - database
    environment:
      DB_HOST: "${DB_HOST:-database}"
      DB_PORT: "${DB_PORT:-3306}"
      DB_USER: "${DB_USER:-mangos}"
      DB_PASS: "${DB_PASS:-mangos}"
      DB_ROOT_PASS: "${DB_ROOT_PASS:-mangos}"
    ports:
      - 8085:8085
    volumes:
      - "./data/mangosd_etc:/opt/cmangos/etc"
      - "/etc/localtime:/etc/localtime:ro"
      - "./extracted-data:/opt/cmangos-data:ro"
