name: Build and Release Container Images

on: push
  # workflow_dispatch: # Allow manual trigger.
  # schedule:
  #   - cron: '0 7 * * *' # Every day at 7am UTC.
  # push:
  #   branches: [ "master" ]

jobs:

  get_latest_cmangos_classic_hash:
    uses: ./.github/workflows/get-cmangos-hash.yml
    with:
      core: classic

  # get_latest_cmangos_tbc_hash:
  #   uses: ./.github/workflows/get-cmangos-hash.yml
  #   with:
  #     core: tbc

  # get_latest_cmangos_wotlk_hash:
  #   uses: ./.github/workflows/get-cmangos-hash.yml
  #   with:
  #     core: wotlk

  build_classic:
    name: Build Classic ${{ matrix.image }}:${{ matrix.image_tag }} - ${{ needs.get_latest_cmangos_classic_hash.outputs.core_hash }}
    needs: get_latest_cmangos_classic_hash
    strategy:
      matrix:
        include:
          - image: extractors
            image_tag: latest

          # - image: realmd
          #   image_tag: latest

          # - image: mangosd
          #   image_tag: latest

          # - image: mangosd
          #   image_tag: "with-playerbot-ahbot"
          #   build_args: |
          #     BUILD_PLAYERBOT=ON
          #     BUILD_AHBOT=ON

          # - image: mangosd
          #   image_tag: "with-playerbot"
          #   build_args: BUILD_PLAYERBOT=ON

          # - image: mangosd
          #   image_tag: "with-ahbot"
          #   build_args: BUILD_AHBOT=ON

    uses: ./.github/workflows/container-build-publish.yml
    with:
      core: classic
      image: mangosd
      image_tag: ${{ matrix.image_tag }}
      build_args: ${{ matrix.build_args }}
      core_hash: ${{ needs.get_latest_cmangos_classic_hash.outputs.core_hash }}