name: Matrix testing

on: push

jobs:

  get_latest_cmangos_classic_hash:
    runs-on: ubuntu-latest
    outputs:
      core_hash: ${{ steps.get_hash.outputs.hash }}
    steps:
      - id: get_hash
        run: git ls-remote https://github.com/cmangos/mangos-classic.git refs/tags/latest | awk '{print "::set-output name=hash::"$1}'

  get_latest_cmangos_tbc_hash:
    runs-on: ubuntu-latest
    outputs:
      core_hash: ${{ steps.get_hash.outputs.hash }}
    steps:
      - id: get_hash
        run: git ls-remote https://github.com/cmangos/mangos-tbc.git refs/tags/latest | awk '{print "::set-output name=hash::"$1}'

  get_latest_cmangos_wotlk_hash:
    runs-on: ubuntu-latest
    outputs:
      core_hash: ${{ steps.get_hash.outputs.hash }}
    steps:
      - id: get_hash
        run: git ls-remote https://github.com/cmangos/mangos-wotlk.git refs/tags/latest | awk '{print "::set-output name=hash::"$1}'

  build_classic_core:
    runs-on: ubuntu-latest
    needs: get_latest_cmangos_classic_hash

    strategy:
      matrix:
        image: [ extractors, realmd, mangosd ]

    steps:
      - name: Placeholder
        run: echo "Placeholder classic.${{ matrix.image }} - ${{ needs.get_latest_cmangos_classic_hash.outputs.core_hash }}"

  build_tbc_core:
    runs-on: ubuntu-latest
    needs: get_latest_cmangos_tbc_hash

    strategy:
      matrix:
        image: [ extractors, realmd, mangosd ]

    steps:
      - name: Placeholder
        run: echo "Placeholder tbc.${{ matrix.image }} - ${{ needs.get_latest_cmangos_tbc_hash.outputs.core_hash }}"

  build_wotlk_core:
    runs-on: ubuntu-latest
    needs: get_latest_cmangos_wotlk_hash

    strategy:
      matrix:
        image: [ extractors, realmd, mangosd ]

    steps:
      - name: Placeholder
        run: echo "Placeholder wotlk.${{ matrix.image }} - ${{ needs.get_latest_cmangos_wotlk_hash.outputs.core_hash }}"