name: Matrix testing

on: push

jobs:

  get_latest_cmangos_classic_hash:
    uses: ./.github/workflows/get-cmangos-hash.yml
    with:
      core: classic

  get_latest_cmangos_tbc_hash:
    uses: ./.github/workflows/get-cmangos-hash.yml
    with:
      core: tbc

  get_latest_cmangos_wotlk_hash:
    uses: ./.github/workflows/get-cmangos-hash.yml
    with:
      core: wotlk

  build_classic_core:
    name: Build Classic Core - ${{ needs.get_latest_cmangos_classic_hash.outputs.core_hash }}
    runs-on: ubuntu-latest
    needs: get_latest_cmangos_classic_hash

    strategy:
      matrix:
        image: [ extractors, realmd, mangosd ]

    steps:
      - name: Placeholder
        run: echo "Placeholder classic.${{ matrix.image }} - ${{ needs.get_latest_cmangos_classic_hash.outputs.core_hash }}"

  build_tbc_core:
    name: Build TBC Core - ${{ needs.get_latest_cmangos_tbc_hash.outputs.core_hash }}
    runs-on: ubuntu-latest
    needs: get_latest_cmangos_tbc_hash

    strategy:
      matrix:
        image: [ extractors, realmd, mangosd ]

    steps:
      - name: Placeholder
        run: echo "Placeholder tbc.${{ matrix.image }} - ${{ needs.get_latest_cmangos_tbc_hash.outputs.core_hash }}"

  build_wotlk_core:
    name: Build WotLK Core - ${{ needs.get_latest_cmangos_wotlk_hash.outputs.core_hash }}
    runs-on: ubuntu-latest
    needs: get_latest_cmangos_wotlk_hash

    strategy:
      matrix:
        image: [ extractors, realmd, mangosd ]

    steps:
      - name: Placeholder
        run: echo "Placeholder wotlk.${{ matrix.image }} - ${{ needs.get_latest_cmangos_wotlk_hash.outputs.core_hash }}"