name: Matrix testing

on: push

jobs:

  get_latest_cmangos_hash:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        variant: [ classic, tbc, wotlk ]

    outputs:
      core_hash: ${{ steps.get_hash.outputs.hash }}

    steps:
      - id: get_hash
        run: git ls-remote https://github.com/cmangos/mangos-${{ matrix.variant }}.git refs/tags/latest | awk '{print "::set-output name=hash::"$1}'

  build_core:
    runs-on: ubuntu-latest
    needs: [ get_latest_cmangos_hash ]

    strategy:
      matrix:
        variant: [ classic, tbc, wotlk ]
        image: [ extractors, realmd, mangosd ]

    steps:
      - name: Placeholder
        run: echo "Placeholder ${{ matrix.variant }}.${{ matrix.image }} - ${{ needs.get_latest_cmangos_hash.outputs.core_hash }}"
